Running "main" (2 tests)...
crash_tests.c:8: Exception: seg_faults_for_null_dereference 
	Test terminated with signal: Segmentation fault

crash_tests.c:13: Exception: will_loop_forever 
	Test terminated unexpectedly, likely from a non-standard exception or Posix signal

Completed "main": 2 exceptions in 2995ms.
